#!/bin/bash
{ ! [[ $1 ]] || [[ $1 =~ ^-.*h ]]; } && { cat <<...k
git_create_berth HOST BERTH PROJECT
  Creates a repo at HOST in the directory
    git/BERTH/PROJECT.
  BERTH can be a multi-level path.
  Creates a corresponding remote named HOST in the local repo.
...k
exit 0; }

ssh "$1" "cd git/ \
  && mkdir -p \"$2\" \
  && cd \"$2\" \
  && mkdir \"$3\" \
  && cd \"$3\" \
  && git init \
  && git config receive.denyCurrentBranch ignore" \
&& git remote add "$1" "$1:git/$2/$3" \
&& git remote show "$1";
